sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t portfolio/dev -f Dockerfile.dev .

script:
  - docker run -e CI=true portfolio/dev npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "AngelLopezPortfolio"
  env: "Angellopezportfolio-env"
  bucket_name: "elasticbeanstalk-us-east-1-096617309970"
  bucket_path: "AngelLopezPortfolio"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY